/*
 * generated by Xtext
 */
package org.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class Langage_whileUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.ui.internal.Langage_whileActivator.getInstance().getInjector("org.xtext.Langage_while");
	}
	
}
