/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Langage_whileUiModule extends org.xtext.ui.AbstractLangage_whileUiModule {
	public Langage_whileUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
