/*
 * generated by Xtext
 */
package org.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.services.Langage_whileGrammarAccess;

public class Langage_whileParser extends AbstractContentAssistParser {
	
	@Inject
	private Langage_whileGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.ui.contentassist.antlr.internal.InternalLangage_whileParser createParser() {
		org.xtext.ui.contentassist.antlr.internal.InternalLangage_whileParser result = new org.xtext.ui.contentassist.antlr.internal.InternalLangage_whileParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getInputAccess().getAlternatives(), "rule__Input__Alternatives");
					put(grammarAccess.getOutputAccess().getAlternatives(), "rule__Output__Alternatives");
					put(grammarAccess.getCommandAccess().getAlternatives(), "rule__Command__Alternatives");
					put(grammarAccess.getEXPRAccess().getAlternatives(), "rule__EXPR__Alternatives");
					put(grammarAccess.getEXPRSIMPLEAccess().getAlternatives(), "rule__EXPRSIMPLE__Alternatives");
					put(grammarAccess.getEXPRSIMPLEAccess().getAlternatives_0(), "rule__EXPRSIMPLE__Alternatives_0");
					put(grammarAccess.getEXPREQAccess().getAlternatives(), "rule__EXPREQ__Alternatives");
					put(grammarAccess.getLCAccess().getAlternatives(), "rule__LC__Alternatives");
					put(grammarAccess.getProgramAccess().getGroup(), "rule__Program__Group__0");
					put(grammarAccess.getProgramAccess().getGroup_1(), "rule__Program__Group_1__0");
					put(grammarAccess.getFunctionAccess().getGroup(), "rule__Function__Group__0");
					put(grammarAccess.getDefAccess().getGroup(), "rule__Def__Group__0");
					put(grammarAccess.getInputAccess().getGroup_0(), "rule__Input__Group_0__0");
					put(grammarAccess.getOutputAccess().getGroup_0(), "rule__Output__Group_0__0");
					put(grammarAccess.getCommandsAccess().getGroup(), "rule__Commands__Group__0");
					put(grammarAccess.getCommandsAccess().getGroup_1(), "rule__Commands__Group_1__0");
					put(grammarAccess.getCommandAccess().getGroup_1(), "rule__Command__Group_1__0");
					put(grammarAccess.getCommandAccess().getGroup_2(), "rule__Command__Group_2__0");
					put(grammarAccess.getCommandAccess().getGroup_3(), "rule__Command__Group_3__0");
					put(grammarAccess.getCommandAccess().getGroup_4(), "rule__Command__Group_4__0");
					put(grammarAccess.getCommandAccess().getGroup_4_8(), "rule__Command__Group_4_8__0");
					put(grammarAccess.getCommandAccess().getGroup_5(), "rule__Command__Group_5__0");
					put(grammarAccess.getVarsAccess().getGroup(), "rule__Vars__Group__0");
					put(grammarAccess.getVarsAccess().getGroup_1(), "rule__Vars__Group_1__0");
					put(grammarAccess.getEXPRSAccess().getGroup(), "rule__EXPRS__Group__0");
					put(grammarAccess.getEXPRSAccess().getGroup_1(), "rule__EXPRS__Group_1__0");
					put(grammarAccess.getEXPRSIMPLEAccess().getGroup_1(), "rule__EXPRSIMPLE__Group_1__0");
					put(grammarAccess.getEXPRSIMPLEAccess().getGroup_2(), "rule__EXPRSIMPLE__Group_2__0");
					put(grammarAccess.getEXPRSIMPLEAccess().getGroup_3(), "rule__EXPRSIMPLE__Group_3__0");
					put(grammarAccess.getEXPRSIMPLEAccess().getGroup_4(), "rule__EXPRSIMPLE__Group_4__0");
					put(grammarAccess.getEXPRSIMPLEAccess().getGroup_5(), "rule__EXPRSIMPLE__Group_5__0");
					put(grammarAccess.getLEXPRAccess().getGroup(), "rule__LEXPR__Group__0");
					put(grammarAccess.getEXPRANDAccess().getGroup(), "rule__EXPRAND__Group__0");
					put(grammarAccess.getEXPRANDAccess().getGroup_1(), "rule__EXPRAND__Group_1__0");
					put(grammarAccess.getEXPRORAccess().getGroup(), "rule__EXPROR__Group__0");
					put(grammarAccess.getEXPRORAccess().getGroup_1(), "rule__EXPROR__Group_1__0");
					put(grammarAccess.getEXPRNOTAccess().getGroup(), "rule__EXPRNOT__Group__0");
					put(grammarAccess.getEXPRNOTAccess().getGroup_0(), "rule__EXPRNOT__Group_0__0");
					put(grammarAccess.getEXPREQAccess().getGroup_0(), "rule__EXPREQ__Group_0__0");
					put(grammarAccess.getEXPREQAccess().getGroup_1(), "rule__EXPREQ__Group_1__0");
					put(grammarAccess.getModelAccess().getGreetingsAssignment(), "rule__Model__GreetingsAssignment");
					put(grammarAccess.getProgramAccess().getFAssignment_0(), "rule__Program__FAssignment_0");
					put(grammarAccess.getProgramAccess().getUAssignment_1_0(), "rule__Program__UAssignment_1_0");
					put(grammarAccess.getProgramAccess().getPpAssignment_1_1(), "rule__Program__PpAssignment_1_1");
					put(grammarAccess.getFunctionAccess().getNAssignment_1(), "rule__Function__NAssignment_1");
					put(grammarAccess.getFunctionAccess().getNomAssignment_2(), "rule__Function__NomAssignment_2");
					put(grammarAccess.getFunctionAccess().getTAssignment_4(), "rule__Function__TAssignment_4");
					put(grammarAccess.getFunctionAccess().getDAssignment_5(), "rule__Function__DAssignment_5");
					put(grammarAccess.getDefAccess().getLAssignment_1(), "rule__Def__LAssignment_1");
					put(grammarAccess.getDefAccess().getInAssignment_2(), "rule__Def__InAssignment_2");
					put(grammarAccess.getDefAccess().getZAssignment_3(), "rule__Def__ZAssignment_3");
					put(grammarAccess.getDefAccess().getVAssignment_5(), "rule__Def__VAssignment_5");
					put(grammarAccess.getDefAccess().getSAssignment_6(), "rule__Def__SAssignment_6");
					put(grammarAccess.getDefAccess().getUAssignment_9(), "rule__Def__UAssignment_9");
					put(grammarAccess.getDefAccess().getOAssignment_10(), "rule__Def__OAssignment_10");
					put(grammarAccess.getInputAccess().getVAssignment_0_0(), "rule__Input__VAssignment_0_0");
					put(grammarAccess.getInputAccess().getZAssignment_0_2(), "rule__Input__ZAssignment_0_2");
					put(grammarAccess.getInputAccess().getInAssignment_0_3(), "rule__Input__InAssignment_0_3");
					put(grammarAccess.getInputAccess().getYAssignment_1(), "rule__Input__YAssignment_1");
					put(grammarAccess.getOutputAccess().getNAssignment_0_0(), "rule__Output__NAssignment_0_0");
					put(grammarAccess.getOutputAccess().getQAssignment_0_2(), "rule__Output__QAssignment_0_2");
					put(grammarAccess.getOutputAccess().getOAssignment_0_3(), "rule__Output__OAssignment_0_3");
					put(grammarAccess.getOutputAccess().getSAssignment_1(), "rule__Output__SAssignment_1");
					put(grammarAccess.getCommandsAccess().getAAssignment_0(), "rule__Commands__AAssignment_0");
					put(grammarAccess.getCommandsAccess().getLAssignment_1_1(), "rule__Commands__LAssignment_1_1");
					put(grammarAccess.getCommandsAccess().getSAssignment_1_2(), "rule__Commands__SAssignment_1_2");
					put(grammarAccess.getCommandAccess().getEAssignment_1_0(), "rule__Command__EAssignment_1_0");
					put(grammarAccess.getCommandAccess().getLAssignment_1_1(), "rule__Command__LAssignment_1_1");
					put(grammarAccess.getCommandAccess().getCAssignment_1_3(), "rule__Command__CAssignment_1_3");
					put(grammarAccess.getCommandAccess().getNAssignment_1_4(), "rule__Command__NAssignment_1_4");
					put(grammarAccess.getCommandAccess().getLlAssignment_2_1(), "rule__Command__LlAssignment_2_1");
					put(grammarAccess.getCommandAccess().getEeAssignment_2_2(), "rule__Command__EeAssignment_2_2");
					put(grammarAccess.getCommandAccess().getCcAssignment_2_3(), "rule__Command__CcAssignment_2_3");
					put(grammarAccess.getCommandAccess().getZAssignment_2_5(), "rule__Command__ZAssignment_2_5");
					put(grammarAccess.getCommandAccess().getKAssignment_2_6(), "rule__Command__KAssignment_2_6");
					put(grammarAccess.getCommandAccess().getLcAssignment_2_7(), "rule__Command__LcAssignment_2_7");
					put(grammarAccess.getCommandAccess().getCcAssignment_3_1(), "rule__Command__CcAssignment_3_1");
					put(grammarAccess.getCommandAccess().getHhAssignment_3_2(), "rule__Command__HhAssignment_3_2");
					put(grammarAccess.getCommandAccess().getTtAssignment_3_3(), "rule__Command__TtAssignment_3_3");
					put(grammarAccess.getCommandAccess().getVvAssignment_3_5(), "rule__Command__VvAssignment_3_5");
					put(grammarAccess.getCommandAccess().getC1Assignment_3_6(), "rule__Command__C1Assignment_3_6");
					put(grammarAccess.getCommandAccess().getSsAssignment_3_7(), "rule__Command__SsAssignment_3_7");
					put(grammarAccess.getCommandAccess().getMmAssignment_4_1(), "rule__Command__MmAssignment_4_1");
					put(grammarAccess.getCommandAccess().getJjAssignment_4_2(), "rule__Command__JjAssignment_4_2");
					put(grammarAccess.getCommandAccess().getKkAssignment_4_3(), "rule__Command__KkAssignment_4_3");
					put(grammarAccess.getCommandAccess().getHgAssignment_4_5(), "rule__Command__HgAssignment_4_5");
					put(grammarAccess.getCommandAccess().getC2Assignment_4_6(), "rule__Command__C2Assignment_4_6");
					put(grammarAccess.getCommandAccess().getGgAssignment_4_7(), "rule__Command__GgAssignment_4_7");
					put(grammarAccess.getCommandAccess().getFfAssignment_4_8_1(), "rule__Command__FfAssignment_4_8_1");
					put(grammarAccess.getCommandAccess().getOAssignment_4_8_2(), "rule__Command__OAssignment_4_8_2");
					put(grammarAccess.getCommandAccess().getDdAssignment_4_8_3(), "rule__Command__DdAssignment_4_8_3");
					put(grammarAccess.getCommandAccess().getSqAssignment_5_1(), "rule__Command__SqAssignment_5_1");
					put(grammarAccess.getCommandAccess().getWxAssignment_5_2(), "rule__Command__WxAssignment_5_2");
					put(grammarAccess.getCommandAccess().getLcAssignment_5_3(), "rule__Command__LcAssignment_5_3");
					put(grammarAccess.getCommandAccess().getLc2Assignment_5_5(), "rule__Command__Lc2Assignment_5_5");
					put(grammarAccess.getCommandAccess().getE1Assignment_5_6(), "rule__Command__E1Assignment_5_6");
					put(grammarAccess.getCommandAccess().getLc3Assignment_5_7(), "rule__Command__Lc3Assignment_5_7");
					put(grammarAccess.getCommandAccess().getLc4Assignment_5_9(), "rule__Command__Lc4Assignment_5_9");
					put(grammarAccess.getCommandAccess().getC3Assignment_5_10(), "rule__Command__C3Assignment_5_10");
					put(grammarAccess.getCommandAccess().getLc5Assignment_5_11(), "rule__Command__Lc5Assignment_5_11");
					put(grammarAccess.getVarsAccess().getAAssignment_0(), "rule__Vars__AAssignment_0");
					put(grammarAccess.getVarsAccess().getLAssignment_1_1(), "rule__Vars__LAssignment_1_1");
					put(grammarAccess.getVarsAccess().getUAssignment_1_2(), "rule__Vars__UAssignment_1_2");
					put(grammarAccess.getEXPRSAccess().getFAssignment_0(), "rule__EXPRS__FAssignment_0");
					put(grammarAccess.getEXPRSAccess().getLAssignment_1_1(), "rule__EXPRS__LAssignment_1_1");
					put(grammarAccess.getEXPRSAccess().getE2Assignment_1_2(), "rule__EXPRS__E2Assignment_1_2");
					put(grammarAccess.getEXPRAccess().getE1Assignment_0(), "rule__EXPR__E1Assignment_0");
					put(grammarAccess.getEXPRAccess().getExAssignment_1(), "rule__EXPR__ExAssignment_1");
					put(grammarAccess.getEXPRSIMPLEAccess().getLAssignment_0_1(), "rule__EXPRSIMPLE__LAssignment_0_1");
					put(grammarAccess.getEXPRSIMPLEAccess().getSAssignment_0_2(), "rule__EXPRSIMPLE__SAssignment_0_2");
					put(grammarAccess.getEXPRSIMPLEAccess().getYyAssignment_1_2(), "rule__EXPRSIMPLE__YyAssignment_1_2");
					put(grammarAccess.getEXPRSIMPLEAccess().getBAssignment_2_2(), "rule__EXPRSIMPLE__BAssignment_2_2");
					put(grammarAccess.getEXPRSIMPLEAccess().getUAssignment_3_2(), "rule__EXPRSIMPLE__UAssignment_3_2");
					put(grammarAccess.getEXPRSIMPLEAccess().getGAssignment_3_3(), "rule__EXPRSIMPLE__GAssignment_3_3");
					put(grammarAccess.getEXPRSIMPLEAccess().getNAssignment_4_3(), "rule__EXPRSIMPLE__NAssignment_4_3");
					put(grammarAccess.getEXPRSIMPLEAccess().getVAssignment_5_1(), "rule__EXPRSIMPLE__VAssignment_5_1");
					put(grammarAccess.getEXPRSIMPLEAccess().getWAssignment_5_2(), "rule__EXPRSIMPLE__WAssignment_5_2");
					put(grammarAccess.getLEXPRAccess().getFAssignment_0(), "rule__LEXPR__FAssignment_0");
					put(grammarAccess.getLEXPRAccess().getNAssignment_1(), "rule__LEXPR__NAssignment_1");
					put(grammarAccess.getLEXPRAccess().getTAssignment_2(), "rule__LEXPR__TAssignment_2");
					put(grammarAccess.getEXPRANDAccess().getFAssignment_0(), "rule__EXPRAND__FAssignment_0");
					put(grammarAccess.getEXPRANDAccess().getLc1Assignment_1_0(), "rule__EXPRAND__Lc1Assignment_1_0");
					put(grammarAccess.getEXPRANDAccess().getLc2Assignment_1_2(), "rule__EXPRAND__Lc2Assignment_1_2");
					put(grammarAccess.getEXPRANDAccess().getEeAssignment_1_3(), "rule__EXPRAND__EeAssignment_1_3");
					put(grammarAccess.getEXPRORAccess().getE1Assignment_0(), "rule__EXPROR__E1Assignment_0");
					put(grammarAccess.getEXPRORAccess().getLc1Assignment_1_0(), "rule__EXPROR__Lc1Assignment_1_0");
					put(grammarAccess.getEXPRORAccess().getLc2Assignment_1_2(), "rule__EXPROR__Lc2Assignment_1_2");
					put(grammarAccess.getEXPRORAccess().getE2Assignment_1_3(), "rule__EXPROR__E2Assignment_1_3");
					put(grammarAccess.getEXPRNOTAccess().getLc1Assignment_0_1(), "rule__EXPRNOT__Lc1Assignment_0_1");
					put(grammarAccess.getEXPRNOTAccess().getE1Assignment_1(), "rule__EXPRNOT__E1Assignment_1");
					put(grammarAccess.getEXPREQAccess().getE1Assignment_0_0(), "rule__EXPREQ__E1Assignment_0_0");
					put(grammarAccess.getEXPREQAccess().getCccAssignment_0_1(), "rule__EXPREQ__CccAssignment_0_1");
					put(grammarAccess.getEXPREQAccess().getLc2Assignment_0_3(), "rule__EXPREQ__Lc2Assignment_0_3");
					put(grammarAccess.getEXPREQAccess().getWAssignment_0_4(), "rule__EXPREQ__WAssignment_0_4");
					put(grammarAccess.getEXPREQAccess().getExAssignment_1_1(), "rule__EXPREQ__ExAssignment_1_1");
					put(grammarAccess.getVariableAccess().getNAssignment(), "rule__Variable__NAssignment");
					put(grammarAccess.getLCsAccess().getAAssignment(), "rule__LCs__AAssignment");
					put(grammarAccess.getLCAccess().getAAssignment_0(), "rule__LC__AAssignment_0");
					put(grammarAccess.getLCAccess().getZAssignment_1(), "rule__LC__ZAssignment_1");
					put(grammarAccess.getLCAccess().getEAssignment_2(), "rule__LC__EAssignment_2");
					put(grammarAccess.getLCAccess().getRAssignment_3(), "rule__LC__RAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.ui.contentassist.antlr.internal.InternalLangage_whileParser typedParser = (org.xtext.ui.contentassist.antlr.internal.InternalLangage_whileParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public Langage_whileGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Langage_whileGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
