/*
 * generated by Xtext
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.services.Langage_whileGrammarAccess;

public class Langage_whileParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private Langage_whileGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.parser.antlr.internal.InternalLangage_whileParser createParser(XtextTokenStream stream) {
		return new org.xtext.parser.antlr.internal.InternalLangage_whileParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public Langage_whileGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Langage_whileGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
