/*
 * generated by Xtext
 */
package org.xtext.ui.contentassist

import org.xtext.ui.contentassist.AbstractLangage_whileProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class Langage_whileProposalProvider extends AbstractLangage_whileProposalProvider {
}
